= OpenAPI Matcher

image:https://github.com/Koriit/openapi-matcher/actions/workflows/build.yaml/badge.svg[Build, link="https://github.com/Koriit/openapi-matcher/actions/workflows/build.yaml"]
image:https://www.codefactor.io/repository/github/koriit/openapi-matcher/badge[CodeFactor,link=https://www.codefactor.io/repository/github/koriit/openapi-matcher]
image:https://img.shields.io/badge/code%20style-%E2%9D%A4-FF4081.svg[ktlint,link=https://ktlint.github.io/]

image:https://img.shields.io/badge/kotlin-1.4.10-blue.svg?logo=kotlin[Kotlin, link=http://kotlinlang.org]
image:https://img.shields.io/maven-central/v/com.koriit.kotlin/openapi-matcher.svg?label=Maven%20Central[Maven Central, link="https://search.maven.org/search?q=g:%22com.koriit.kotlin%22%20AND%20a:%22openapi-matcher%22"]
image:https://img.shields.io/github/license/koriit/openapi-matcher[GitHub]

WARNING: From version 0.7.0 all package names have been renamed to match new artifact group id.

OpenAPI matcher for Kotlin allows comparing 2 specifications against each other.

[WARNING]
This library in *Work In Progress*. It doesn't support all elements of OpenAPI specification yet. The support scope can be
checked individually for every OpenAPI specification object in the `korrit.kotlin.openapi.model` package.


== Reading OpenAPI
This library includes an OpenAPI reader that allows parsing your OpenAPI specification in YAML format into
an in-memory object that can be used in a matcher.

[source,kotlin]
----
val doc: OpenAPI = OpenAPIReader().load({}.javaClass.getResourceAsStream("/openapi.yaml"))
----

[NOTE]
Unsupported elements are ignored.

== Validating OpenAPI
Once you have 2 OpenAPI objects you can match them checking for any significant differences.

A significant difference is understood as a divergence that leads to or may lead to a compatibility break.

The general idea is to validate your OpenAPI specification against your code instead of spec/code generation.

[source,kotlin]
----
val source: OpenAPI = ... // Analyze your code

LOG.info("Reading OpenAPI spec...")
val doc: OpenAPI = OpenAPIReader().load({}.javaClass.getResourceAsStream("/openapi.yaml"))

LOG.info("Validating spec...")
val errors = OpenAPIMatcher().match(doc, source)

if (errors.isNotEmpty()) {
    LOG.info("Result of code analysis:\n{}", source)

    errors.forEach {
        LOG.error(it)
    }

    fail("There are ${errors.size} validation errors!")
} else {
    LOG.info("OK!")
}
----

