= OpenAPI Matcher

image:https://www.travis-ci.org/Koriit/openapi-matcher.svg?branch=master["Build Status", link="https://www.travis-ci.org/Koriit/openapi-matcher"]
image:https://www.codefactor.io/repository/github/koriit/openapi-matcher/badge[CodeFactor,link=https://www.codefactor.io/repository/github/koriit/openapi-matcher]
image:https://img.shields.io/badge/code%20style-%E2%9D%A4-FF4081.svg[ktlint,link=https://ktlint.github.io/]

image:https://api.bintray.com/packages/koriit/kotlin/openapi-matcher/images/download.svg[Download, link=https://bintray.com/koriit/kotlin/openapi-matcher/_latestVersion]
image:https://img.shields.io/github/license/koriit/openapi-matcher[GitHub]

OpenAPI matcher for Kotlin, allows to compare 2 specifications against each other.

[WARNING]
This library in *Work In Progress*. It doesn't support all elements of OpenAPI specification yet. Support scope can be
checked individually for every OpenAPI specification object in `korrit.kotlin.openapi.model` package.


== Reading OpenAPI
This library includes OpenAPI reader that allows to parse your OpenAPI specification in YAML format into
in-memory object that can be used in matcher.

[source,kotlin]
----
val doc: OpenAPI = OpenAPIReader().load({}.javaClass.getResourceAsStream("/openapi.yaml"))
----

[NOTE]
Unsupported elements are ignored.

== Validating OpenAPI
Once you have 2 OpenAPI objects you can match them checking for any significant differences.

Significant difference is understood as divergence that leads or may lead to compatibility break.

The general idea is to validate your OpenAPI specification against your code instead of spec/code generation.

[source,kotlin]
----
val source: OpenAPI = ... // Analyze your code

LOG.info("Reading OpenAPI spec...")
val doc: OpenAPI = OpenAPIReader(javaClass.getResourceAsStream("/openapi.yaml")).load()

LOG.info("Validating spec...")
val errors = OpenAPIMatcher().match(doc, source)

if (errors.isNotEmpty()) {
    LOG.info("Result of code analysis:\n{}", source)

    errors.forEach {
        LOG.error(it)
    }

    fail("There are ${errors.size} validation errors!")
} else {
    LOG.info("OK!")
}
----

